### ISSUE TITLE
little bug with meshnode.py

### ISSUE THREAD

**Issue by shuangwuhang** [JintaoLee-Roger/cigvis#20] opened 2024-09-19 07:23 UTC
# ArbLineNode
##Check data and volume
        if data is not None and volume is not None:
            warnings.warn(
                "Both 'data' and 'volume' are provided. Using 'data'.",
                category=UserWarning)
        elif data is None and volume is None:
            raise ValueError("Either 'data' or 'volume' must be provided.")

        self.data = data
        self.volume = volume

        if self.path is None:
            **self.path = surfaceutils.interpolate_path(self.anchor)**
    
        if self.data is None:
          
            pout, pdata = surfaceutils.extract_data(self.volume, self.path)
            self.data = surfaceutils.interp_arb(pout, pdata)

surfaceutils.interpolate_path(self.anchor) will return a tuple value,  maybe fixed by 
            **self.path, _ = surfaceutils.interpolate_path(self.anchor)**

**Comment by JintaoLee-Roger** [comment] 2024-10-22 11:25
Thank you for pointing out this bug, it is caused by updating surfaceutils but not updating meshnodes at the same time. This will be fixed in the next release!

**Comment by JintaoLee-Roger** [comment] 2024-11-25 08:33
Hi!
This bug has been fixed by [v0.1.4](https://github.com/JintaoLee-Roger/cigvis/tree/v0.1.4)

**Closed as completed by JintaoLee-Roger** 2024-11-25 08:33 UTC
